name: aibas
description: An Incremental Backup App with Subversion.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.2
  dotted_border: ^2.0.0+3
  drag_and_drop_windows: ^0.0.2
  dynamic_color: ^1.5.4
  file_picker: ^5.2.4
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_riverpod: ^2.1.1
  flutter_speed_dial: ^6.2.0
  flutter_treeview: ^1.0.7+1
  freezed_annotation: ^2.2.0
  hooks_riverpod: ^2.1.1
  intl: ^0.18.0
  json_serializable: ^6.5.4
  linear_step_indicator: ^1.0.0+3
  pedantic_mono: ^1.20.0
  window_manager: ^0.2.8

dev_dependencies:
  build_runner: ^2.3.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2

flutter:
  uses-material-design: true
  fonts:
    - family: M PLUS 1
      fonts:
        - asset: assets/fonts/MPLUS1-Medium.ttf
          weight: 500
        - asset: assets/fonts/MPLUS1-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/MPLUS1-Bold.ttf
          weight: 700
        - asset: assets/fonts/MPLUS1-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/MPLUS1-Black.ttf
          weight: 900
